services:
  - type: web
    name: carecompanion-translation
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: API_KEY
        fromSecret: <your-secret-name> # For security, use Render secrets
