services:
  - type: web
    name: carecompanion-summarizer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: API_KEY
        fromSecret: <your-secret-name> # For security, use Render secrets
